version: "3.7"
services:

  car-service:
    build: ./car-service
    image: xml/car-service:1.0.0
    container_name: car-service
    restart: on-failure
    networks:
      - xml
    ports:
      - 8081:8081
    environment:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: admin
      DATABASE_DOMAIN: postgres
      DATABASE_SCHEMA: postgres
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka/
    depends_on: 
      - postgres
      - eureka-service

  eureka-service:
    build: ./eureka
    image: xml/eureka:1.0.0
    container_name: eureka-service
    restart: on-failure
    networks:
      - xml
    ports:
      - 8761:8761
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka/
    

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    networks:
      - xml

    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin

networks:
  xml:
    name: xml
    driver: bridge
