//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.11 at 10:39:43 PM CEST 
//


package xmlteam4.userservice.soap.classes;

import localhost._8085.xml_user_service_schema.GetMessagesRequest;
import localhost._8085.xml_user_service_schema.GetMessagesResponse;
import localhost._8085.xml_user_service_schema.Message;
import localhost._8085.xml_user_service_schema.MessageRequest;
import localhost._8085.xml_user_service_schema.MessageResponse;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the localhost._8085.xml_user_service_schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: localhost._8085.xml_user_service_schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link localhost._8085.xml_user_service_schema.MessageRequest }
     * 
     */
    public localhost._8085.xml_user_service_schema.MessageRequest createMessageRequest() {
        return new MessageRequest();
    }

    /**
     * Create an instance of {@link localhost._8085.xml_user_service_schema.MessageResponse }
     * 
     */
    public localhost._8085.xml_user_service_schema.MessageResponse createMessageResponse() {
        return new MessageResponse();
    }

    /**
     * Create an instance of {@link localhost._8085.xml_user_service_schema.GetMessagesRequest }
     * 
     */
    public localhost._8085.xml_user_service_schema.GetMessagesRequest createGetMessagesRequest() {
        return new GetMessagesRequest();
    }

    /**
     * Create an instance of {@link localhost._8085.xml_user_service_schema.GetMessagesResponse }
     * 
     */
    public localhost._8085.xml_user_service_schema.GetMessagesResponse createGetMessagesResponse() {
        return new GetMessagesResponse();
    }

    /**
     * Create an instance of {@link localhost._8085.xml_user_service_schema.Message }
     * 
     */
    public localhost._8085.xml_user_service_schema.Message createMessage() {
        return new Message();
    }

}
